general:
  ignore_unknown: true
  comparison_table: true
  ignore_file: true
  chinese_traditional: true
  default_output: "../testspace/default/"
  proxies: {}
  original_archive_dir: "../testspace/orig"
  monitor_dir: "../testspace/input"

features:
  move_original: true
  subset_ass: true
  auto_sort: false

tmdb:
  api: "!env TMDB_API_KEY"
  manual: false

ai:
  provider: deepseek
  api: "!env AI_API_KEY"
  call: false
  prompt1: |
    请你解析这个番剧文件名，最后只返回提取的番剧名称，不使用别名，不包含季数、集数和标题，也不需要翻译，注意与字幕组区分。
    例如：
      "[LKSUB][mono][11][1080P]" → "mono"
      "[DMG&VCB-Studio] Kono Subarashii Sekai ni Bakuen wo! [1080p]" → "Kono Subarashii Sekai ni Bakuen wo!"
      "SAKAMOTO DAYS 1080p" → "SAKAMOTO DAYS"
  prompt2: |
    请你根据我发送的相关信息解析这个番剧文件名，最后只返回番剧的季数对应的阿拉伯数字，
    默认为 1，注意不要与集数搞混。

ignore_exts: 
  - ".flac"
  - ".mp3"
  - ".cue"
  - ".log"
  - ".jpg"
  - ".png"
  - ".webp"
  - ".7z"
  - ".zip"
  - ".rar"
  - ".DS_Store"


