general:
  ignore_unknown_files: true
  generate_comparison_table: true
  generate_ignore_file: true
  trad_chinese: true
  default_output: "./test/default/"
  proxies: {}

tmdb:
  api: "!env TMDB_API_KEY"
  selected: false

ai:
  provider: "deepseek"
  api: "!env AI_API_KEY"
  call: false

features:
  hardlink: true
  dryrun: true

ignore_exts: 
  - ".flac"
  - ".mp3"
  - ".cue"
  - ".log"
  - ".jpg"
  - ".png"
  - ".webp"
  - ".7z"
  - ".zip"
  - ".rar"
  - ".DS_Store"
